theme: encommuns-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  search:
    active: true
  posts:
    index: 
      layout: grid
