theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  search:
    active: true
  posts:
    index: 
      layout: grid
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-blanc.svg"